services:
  - type: web
    name: ramadan-quiz
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: ramadan-quiz-redis
          property: connectionString
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        generateValue: true
      - key: NODE_ENV
        value: production

  - type: redis
    name: ramadan-quiz-redis
    region: frankfurt
    plan: free
    ipAllowList: []
